name: Employee App CI-CD

on:

 pull_request:
   branches:
     - main

 push:
   branches:
     - main

jobs:

 build-test:

   runs-on: ubuntu-latest

   defaults:
     run:
       working-directory: backend

   steps:

     - name: Checkout
       uses: actions/checkout@v4

     - name: Setup Node
       uses: actions/setup-node@v4
       with:
         node-version: 20

     - name: Install Dependencies
       run: npm install

     - name: Run Lint
       run: npm run lint

     - name: Run Tests
       run: npm test

     - name: Build Docker Backend
       run: docker build -t employee-backend .

 deploy-frontend:

   needs: build-test

   if: github.ref == 'refs/heads/main'

   runs-on: ubuntu-latest

   permissions:
     pages: write
     id-token: write

   environment:
     name: github-pages

   steps:

     - name: Checkout
       uses: actions/checkout@v4

     - name: Upload Frontend
       uses: actions/upload-pages-artifact@v3
       with:
         path: ./frontend

     - name: Deploy Pages
       uses: actions/deploy-pages@v4
